sudo: required
dist: trusty
language: c

matrix:
  include:
   - compiler: gcc-4
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-4.9
           - check
     env: COMPILER=gcc-4.9
   - compiler: gcc-5
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-5
           - check
     env: COMPILER=gcc-5
   - compiler: gcc-6
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-6
           - check
     env: COMPILER=gcc-6
         - CMAKE_EXTRA_FLAGS="-DCMAKE_EXE_LINKER_FLAGS='-coverage'" 
         - CMAKE_EXTRA_C_FLAGS="-coverage"
         - COVERAGE=t
   - compiler: clang-3.6
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-5
           - check
     env: 
         - COMPILER=$HOME/llvm/clang+llvm-3.6.0-x86_64-linux-gnu/bin/clang
         - DOWNLOAD=http://releases.llvm.org/3.6.0/clang+llvm-3.6.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
   - compiler: clang-3.7
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-5
           - check
     env: 
         - COMPILER=$HOME/llvm/clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang
         - DOWNLOAD=http://releases.llvm.org/3.7.0/clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
   - compiler: clang-3.8
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-5
           - check
     env: 
         - COMPILER=$HOME/llvm/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang
         - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/llvm/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/lib
         - DOWNLOAD=http://releases.llvm.org/3.8.0/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
cache:
    directories:
        - $HOME/llvm
before_install:
  - sudo apt-get update -qq
  - if [[ -n "$DOWNLOAD" ]] ; then if [[ ! -e "$COMPILER" ]] ; then cd $HOME; curl -o tarball.tar.xz $DOWNLOAD && cd $HOME/llvm && tar xf $HOME/tarball.tar.xz ; fi ; fi
  - CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.0-rc2-Linux-x86_64.tar.gz"
  - cd $HOME && curl -o cmake-tarball.tar.gz ${CMAKE_URL} && mkdir -p $HOME/cmake && cd $HOME/cmake && tar xf $HOME/cmake-tarball.tar.gz --strip-components=1 && export PATH=${PWD}/bin:${PATH}

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir travis-build && cd travis-build
  - cmake -DDEPENDENCIES_PREINSTALLED=ON -DCMAKE_C_COMPILER="$COMPILER" -DGOTCHA_ENABLE_TESTS=TRUE $CMAKE_EXTRA_FLAGS -DCMAKE_C_FLAGS="$CMAKE_EXTRA_C_FLAGS -Wall -Werror -Wextra -Wno-unused-variable -Wno-missing-field-initializers" ../
  - make -j VERBOSE=1
  - ctest --verbose

after_success:
  - if [[ -n "${COVERAGE}" ]] ; then bash <(curl -s https://codecov.io/bash) ; fi
